### ISSUE TITLE
Theme doesn't render on Windows Phone

### ISSUE THREAD

**Issue by antranapp** [commadelimited/jQuery-Mobile-Bootstrap-Theme#2]
The theme doesn't render on Windows Phone. I tested it on Samsung Focus running Windows Mango in a PhoneGap App but everything is black. The original theme of jQuery Mobile works fine.

**Comment by commadelimited** [comment]
peacemoon, can you confirm which version of jQuery Mobile you're using, and which version of the bootstrap theme?

A screenshot of the page which is broken would also be helpful.

**Comment by antranapp** [comment]
Hi, i use jquery mobile 1.1, lastest bootstrap theme from master.

Screenshot here: http://img137.imageshack.us/img137/2156/img20120504142210.jpg

**Comment by commadelimited** [comment]
Very interesting. When you preview it on your desktop does it work okay?

Is there a link online that I can view on my iPhone?

**Comment by antranapp** [comment]
yes, you can test it at http://yeah.pagodabox.com/m/

**Comment by commadelimited** [comment]
I just remembered that when the jQuery Mobile team upgraded to 1.1 they also made changes to ThemeRoller. Can you do this...

1) Go to http://jquerymobile.com/themeroller/
2) Click the "Import or Upgrade" button at the top.
3) Paste in the uncompressed Bootstrap CSS file.
4) Export it and try that CSS file in your site.

If that fixes the problem please let me know and I'll upgrade the entire theme and credit you for the find.

**Comment by antranapp** [comment]
i tried it but it still doesn't work. I have also tried it with desktop ie9 and the website just looks the same as on Windows Phone (only black). I will compare the theme with the original one and see whether i can track down the root cause.

**Comment by commadelimited** [comment]
Just curious but does the standard jquery mobile theme work on windows mobile?

**Comment by antranapp** [comment]
Yes, the standard theme works as expected. 

Your demo site (http://andymatthews.net/code/jQuery-Mobile-Bootstrap-Theme/)  also doesn't render correctly on both my windows phone and my desktop IE9.  (see images) http://img694.imageshack.us/img694/5510/20120507100530.jpg 
http://img844.imageshack.us/img844/829/20120507101619.jpg

**Comment by commadelimited** [comment]
peacemoon...

Would you please go back to my demo site and review the styles again? I spent some time adding in some IE and MS specific gradient definitions and I'd like to check and see if that fixes your problem.

http://andymatthews.net/code/jQuery-Mobile-Bootstrap-Theme/

**Comment by antranapp** [comment]
Hi Andy,

i still have the same issue. I think for Windows Phone Mango and IE9, you should use this css rule for gradient:

filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr='#ffffff', endColorstr='#000000');/_For IE7-8-9_/ 

But when searching around, i found this: https://github.com/jquery/jquery-mobile/issues/2046 . This means, for IE9 and Windows Mango, we need non-gradient background color. 

I will try to debug more to fix the problem, just have so little time right now.

**Comment by antranapp** [comment]
Hi Andy,

i fix the theme and send a pull request. Hope that it is helpful.

**Comment by commadelimited** [comment]
Great job peacemoon, thank you. I've merged in your changes. Can you confirm that the theme now works correctly on Mango?

**Comment by antranapp** [comment]
My site renders correctly now on Windows Phone and Desktop IE9.

http://img708.imageshack.us/img708/7936/20120510221618.jpg

http://img36.imageshack.us/img36/7144/20120510221214.jpg

I still have problem with your demo page (just in case you haven't update your demo page)

**Comment by commadelimited** [comment]
Just updated it...in fact I did a major update. You're the only one I know with a windows phone. Would you mind checking it out?

**Comment by antranapp** [comment]
i just have seen the update, your demo works fine on my desktop but the icons are not shown, both on my windows phone and my android phone. 

https://docs.google.com/open?id=0BxSa3DZxwXX-WnVNTEwyOVpOSW8

Web version (seen on Chrome 18, Windows 7) is however ok.

**Comment by commadelimited** [comment]
Interesting. Both phones show the white square in place of the icon? Wonder if they don't understand UTF encoding. 

When you go to this page on your phone do you see the icons:
http://fortawesome.github.com/Font-Awesome/
